config/routes.rb
Rails.application.routes.draw do
  get '/' => 'site#home'
  
  resources :projects do
    resources :entries
  end
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :project

  validates :hours, numericality: true, presence: true
  validates :minutes, numericality: true, presence: true
  validates :date, presence: true
  validates :project, presence: true

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_attached_file :logo, styles: {:medium => "300x300>", :thumb => "100x100>"}
  validates_attachment_content_type :logo, :content_type => /\Aimage\/.*\Z/

  has_many :entries

  validates :name, presence: true, uniqueness: true
  validates :name, length: { maximum: 30 }
  validates :name, format: { with: /\A[a-zA-Z0-9\s]+\z/,
    message: "only allows letters and numbers and spaces" }
  
  def self.iron_find (id)
    where(id: id).first
  end

  def self.clean_old
    from = Time.now.midnight - 1.week
    where("created_at > ?", from).destroy_all
  end

  def self.last_created_projects(n)
    where("created_at < ?", Time.now).limit(n)
  end

  def total_number_of_hours_for_month(month, year)
    first_of_month = Date.new(year, month, 1)
    last_of_month = Date.new(year, month, -1)
    month_entries = self.entries.where(created_at: first_of_month..last_of_month)
    sum_hours = 0
    sum_minutes = 0
    month_entries.each do |entry|
      sum_hours += entry.hours
      sum_minutes += entry.minutes
    end
    sum_hours += sum_minutes/60
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def index
    @project = Project.find params[:project_id]
    @entries = @project.entries
  end

  def show
    @entry = Entry.find(params[:id])
  end

  def new
    @project = Project.find params[:project_id]
    @entry = @project.entries.new
  end

  def create
    @project = Project.find params[:project_id]
    @entry = @project.entries.new entry_params
    if @entry.save
      flash[:notice] = "Entry created sucessfully."
      redirect_to action: 'index', controller: 'entries', project_id: @project.id
    else
      render 'new'
    end
  end

  def edit
    @project = Project.find params[:project_id]
    @entry = @project.entries.find params[:id]
  end

  def update
  @entry = Entry.find(params[:id])
    if @entry.update_attributes entry_params
      flash[:notice] = "Entry updated successfully"
      redirect_to action: 'index'
    else
      flash.now[:errors] = @entry.errors.full_messages
      render 'edit'
    end
  end

  private

  def entry_params
    params.require(:entry).permit(:hours, :minutes, :date)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.last_created_projects(10)
    if @projects.empty?
      render 'no_projects'
    end
  end

  def show
    begin
      @project =  Project.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      render 'no_project_found'
    end
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new project_params
    if @project.save
      redirect_to action: 'index'
    else
      render 'new'
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.update_attributes project_params
      redirect_to action: 'index'
    else
      render 'new'
    end
  end

  private

  def project_params
    params.require(:project).permit(:name, :description, :logo)
  end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def home
    'home'
  end

  def contact
    'contact'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/entries/_form.html.erb
<%= form_for [@project, @entry] do |f| %>
  <%= f.label :hours %>
  <%= f.text_field :hours, size: 4 %>
  <br>
  <%= f.label :minutes %>
  <%= f.text_field :minutes, size: 4 %>
  <br>
  <%= f.label :date %>
  <%= f.date_field :date, size: 4 %>
  <br>
  <%= f.submit 'Save' %>
  <%= link_to 'Cancel', project_entries_path(@project) %>
<% end %>

app/views/entries/edit.html.erb
<h2>Editing an existing entry in <%= @project.name %> project</h2>

<%= render 'form' %>

app/views/entries/index.html.erb
<% if flash[:notice] %>
  <%= flash[:notice] %>
<% end %>

<h2><%= link_to(@project.name, project_entries_path(@project)) %></h2>

<ul>
  <% @entries.each do |entry| %>
    <li>
      <%= link_to("Edit", edit_project_entry_path(@project, entry)) %>
      <%= format("%.2d",entry.hours) %> h
      <%= format("%.2d",entry.minutes) %> m -
      <%= entry.date.strftime("%Y-%m-%d") %>
      <%= link_to('Delete', project_entry_path(@project, entry), method: :delete, confirm: 'Are you sure?') %>
    </li>
  <% end %>
</ul>

<%= link_to("Create a new entry.", new_project_entry_path) %><br>
<%= link_to("Back to the list of projects.", projects_path) %>

app/views/entries/new.html.erb
<% if @entry.errors.any? %>
  <ul>
    <% @entry.errors.full_messages.each do |error_msg| %>
      <li><%= error_msg %></li>
    <% end %>
  </ul>
<% end %>

<h2>Creating a new entry in <%= @project.name %> project</h2>

<%= render 'form' %>

app/views/entries/show.html.erb
<%=@entry.hours%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Timetracking</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <h1>The Timekeeper</h1>

<%= yield %>

</body>
</html>

app/views/projects/edit.html.erb
<h2>Edit this existing project.</h2>

<%= form_for @project, :html => { :multipart => true } do |f| %>
  <%= f.label :logo %> 
  <%= f.file_field :logo %>
  <br>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <br>
  <%= f.submit 'Save' %>
<% end %>

app/views/projects/index.html.erb
<h2>Here is a list of current projects.</h2>

<ul>
  <% @projects.each do |project| %>
    <% if project.description.present? %>
      <li><%= link_to("Edit", edit_project_path(project)) %><%= image_tag project.logo.url(:thumb) %><b><%= link_to(project.name, project_entries_path(project)) %></b> -
        <%= project.description %></li>
    <% else %>
      <li><%= link_to("Edit", edit_project_path(project)) %><%= image_tag project.logo.url(:thumb) %><b><%= link_to(project.name, project_entries_path(project)) %></b></li>
    <% end %>
  <% end %>
</ul>

app/views/projects/new.html.erb
<% if @project.errors.any? %>
  <ul>
    <% @project.errors.full_messages.each do |error_msg| %>
      <li><%= error_msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @project, :html => { :multipart => true } do |f| %>
  <%= f.label :logo %> 
  <%= f.file_field :logo %>
  <br>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <br>
  <%= f.submit 'Save' %>
<% end %>

app/views/projects/no_project_found.html.erb
<h1>These are not the droids you're looking for...</h1>

app/views/projects/show.html.erb
<h2>Project Profile</h2>

<h3><%= @project.name %></h3>
  
<p><%= @project.description %></p>

app/views/site/contact.html.erb
<h1>If you like 'em big and bald,</h1>
<h2>you can reach Seanie here...</h2>
<p>seaniechaos@gmail.com</p>

app/views/site/home.html.erb
<h2>Welcome to this time tracking tool</h2>

<p>Ironhack powered</p>

app/views/site/list.html.erb
<h1>List</h1>

<ul>
<% @projects.each do |p| %>
  <p>pj.name</p>
</ul>>

app/views/site/projects.html.erb
<h1>PROJECTS</h1>